### ISSUE TITLE
Backend can not be launced

### ISSUE THREAD

**Issue by Maximus169** [Pavel-Innokentevich-Galanin/react-express-webradio#3]
![image](https://user-images.githubusercontent.com/19841564/140622631-21ab8f5a-feb9-415b-b709-c66a570b37f0.png)
Вот такое вижу при запуске бэкенда

**Comment by Pavel-Innokentevich-Galanin** [comment]
`NODEJS_BASEURL` и `NODEJS_LOCALE_PORT` прописаны в файле `copy.env`. Эти переменные должны быть прописаны в `.env`. Нужно сделать копирование: `cp copy.env .env`.

Это копирование есть в Makefile.

Когда мы скачали репозиторий, то нужно выполнить команды

```bash
cd src
make install
```

Эта информация о командах была указана в корне репозитория в `READEME.md`.

**Comment by Maximus169** [comment]
Точно, пропустил. Извиняюсь
