### ISSUE TITLE
Add audio visualization

### ISSUE THREAD

**Issue by Maximus169** [Pavel-Innokentevich-Galanin/react-express-webradio#5]
Было бы прикольно, если бы музыка была визуализирована как нибудь графически на фронтенде.
Примеры:
https://www.npmjs.com/package/react-audio-spectrum
https://betterprogramming.pub/using-react-ui-components-to-visualize-real-time-spectral-data-of-an-audio-source-17a498a6d8d7

Наиболее симпотичные варианты это либо волни, либо флейм граф

**Comment by Pavel-Innokentevich-Galanin** [comment]
Когда мы используем `howler`

```jsx
import { Howl } from "howler";
```

```jsx
const hwr = new Howl({
    src: [
        "",
        //массив строк с музыкой
    ],
    html5: true,
});
```

то манипулируем так

```jsx
hwr.play();
hwr.pause();
hwr.stop();
```

---

Для работы визуализации в `react-audio-spectrum` нам нужен `id`, для того, чтобы при `play()` и `pause()` отлавливалась визуализация. При `howler` тег `audio` не создается. `id` не узнать.

---

Был найден вариант без использования библиотеки `howler`. Используем чистый `html` тег `audio` и `document.getElementById("")`.
Так как мы используем в React функциональные компоненты, а не class, то у нас нет метода `ComponentDidMount()`, в котором мы прописываем `document.getElementById("")` . Не используя класс, а используя функциональную компоненту, было найдено решение, используя `ref`.

```jsx
import { useState, useRef } from 'react';
import AudioSpectrum from 'react-audio-spectrum';
```

```jsx
const [gpi_radioIsPlay, gpi_setRadioIsPlay] = useState(false);
const gpi_audio_ref = useRef(null);
```

```jsx
function gpi_play_pause() {
    if (gpi_radioIsPlay) {
        document.getElementById(gpi_audio_ref.current.id).pause();
        gpi_setRadioIsPlay(false);
        return;
    }
    document.getElementById(gpi_audio_ref.current.id).play();
    gpi_setRadioIsPlay(true);
}
```

```jsx
<audio
    id="gpi-audio"
    crossorigin="anonymous"
    ref={gpi_audio_ref}
    src={``}
/>
<AudioSpectrum
    audioId={'gpi-audio'}
/>
```

---

Чтобы не было ошибки

```
The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence.
```

в тег `audio` был добавлен атрибут

```jsx
<audio crossorigin="anonymous" />
```
